{% set name = "signalr-client-aio" %}
{% set version = "0.0.1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/signalr-client-aio-{{ version }}.tar.gz
  sha256: d73bb978c367ed1b0ee4a262cf6cbda71281a0c540c1ba9a0b931815d1bac3d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.18.4
    - websockets >=4.0.1

test:
  imports:
    - signalr_aio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/slazarov/python-signalr-client
  summary: Simple python SignalR client using asyncio.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
